data:
  raw_dir: "00_data/00a_raw"

fbref:
  leagues:
    LaLiga_ESP: "ESP-La Liga"
    PremierLeague_ENG: "ENG-Premier League"
    #SerieA_ITA: "ITA-Serie A"
    #Ligue1_FRA: "FRA-Ligue 1"
    #Bundesliga_GER: "GER-Bundesliga"
    #LaLiga2_ESP: "ESP-Segunda Division"
    #Eredivisie_NED: "NED-Eredivisie"
    #UCL_UEFA: "UEFA-Champions League"

  seasons:
    #"2025-26": 2025
    #"2024-25": 2024
    #"2023-24": 2023
    "2022-23": 2022
    "2021-22": 2021
    "2020-21": 2020

  # enable/disable blocks
  enable_league_init: true
  enable_lineups: true
  enable_player_match: false
  enable_player_season: false
  enable_team_match: true
  enable_team_season: true

logging:
  verbose: true
